name: Publish release
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  publish-release:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/lukasturcani/smores-testing-environment:latest
    env:
      VERSION: ${{ github.ref_name }}
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Install smores
        run: |
          . /deps/venv/bin/activate
          pip install --no-deps -e .
      - name: Build smores
        run: |
          . /deps/venv/bin/activate
          python -m build
      - name: Publish smores
        run: >
          . /deps/venv/bin/activate

          twine upload
          -u ${{ secrets.PYPI_USERNAME }}
          -p ${{ secrets.PYPI_PASSWORD }}
          dist/*
