name: Tests
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  ruff:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/lukasturcani/atomlite-testing-environment:latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Install atomlite
        run: |
          . /deps/venv/bin/activate
          pip install --no-deps -e .
      - name: Run ruff
        run: |
          . /deps/venv/bin/activate
          ruff .
  mypy:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/lukasturcani/atomlite-testing-environment:latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Install atomlite
        run: |
          . /deps/venv/bin/activate
          pip install --no-deps -e .
      - name: Run mypy
        run: |
          . /deps/venv/bin/activate
          mypy .
  black:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/lukasturcani/atomlite-testing-environment:latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Install atomlite
        run: |
          . /deps/venv/bin/activate
          pip install --no-deps -e .
      - name: Run black
        run: |
          . /deps/venv/bin/activate
          black --check .
  pytest:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/lukasturcani/atomlite-testing-environment:latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Install atomlite
        run: |
          . /deps/venv/bin/activate
          pip install --no-deps -e .
      - name: Run pytest
        run: |
          . /deps/venv/bin/activate
          pytest --cov=src --cov-report term-missing
  doctest:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/lukasturcani/atomlite-testing-environment:latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Install atomlite
        run: |
          . /deps/venv/bin/activate
          pip install --no-deps -e .
      - name: Run doctest
        run: |
          . /deps/venv/bin/activate
          make -C docs doctest
